config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'

  resources :posts do
    resources :comments
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
    has_many :posts
    has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def new
    @comment = Comment.new
    @post = Post.find(params[:post_id])
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create!(comment_params)
    redirect_to post_path(@post)
  end
  def show
    @comment = Comment.find(params[:id])
    @post = Post.find(params[:post_id])
  end
  def update
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @comment.update(comment_params)
    redirect_to post_path(@post)
  end
  def edit
    @comment = Comment.find(params[:id])
    @post = Post.find(params[:post_id])
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  private
  def comment_params
    params.require(:comment).permit(:subject, :content, :author)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
      @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.create!(post_params)
    redirect_to posts_path
  end
  def show
    @comments = Comment.all
    @post = Post.find(params[:id])
  end

  def edit
      @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:id])
    @comments = @post.comments
    @comments.each do |comment|
      comment.destroy
    end
    @post.destroy
    redirect_to posts_path
  end

  private

    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:title, :content, :author)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/edit.html.erb
<h2>Edit Comment</h2>

<%= form_for [@post,@comment] do |f| %>
  <%= f.label :subject %>
  <%= f.text_field :subject %>

  <%= f.label :content%>
  <%= f.text_area :content, size: "90x12" %>

  <%= f.submit %>
<% end %>

<%= form_for [@post,@comment], method: :delete do |f| %>
  <%= f.submit "Delete!", class: "delete" %>
<% end %>

app/views/comments/new.html.erb
<h2>New Comment</h2>
<%= form_for [@post,@comment] do |f| %>
  <%= f.label :subject %>
  <%= f.text_field :subject %>

  <%= f.label :content%>
  <%= f.text_area :content, size: "90x12" %>

  <%= f.label :author %>
  <%= f.text_field :author %>

  <%= f.submit "Submit Comment" %>
<% end %>

app/views/comments/show.html.erb
<h2><%=@comment.subject%>
  <% if @comment.post.user == current_user %>
  <%= link_to "(edit)",edit_post_comment_path(@post, @comment)%>
  <% end %>
</h2>

<p><%=@comment.content%></p>
<p><%=@comment.author%></p>
<p>Created: <%= @comment.created_at %>,  Last updated: <%= @comment.updated_at %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Scribble</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Roboto&subset=latin,latin-ext' rel='stylesheet' type='text/css'>

</head>
<body>

<header>
<div class = "center">
  <%= link_to image_tag("https://camo.githubusercontent.com/c0fa788c04276e154ec92e5ea05aa5c6692f43ea/68747470733a2f2f646c2e64726f70626f7875736572636f6e74656e742e636f6d2f732f386672663872626c7736706e7064732f686970737465726c6f676f67656e657261746f725f313433383030373038373739332e706e673f646c3d30"), posts_path %>
</div>
<h5>
  <% if current_user %>
  Signed in as <%= "#{current_user.email}" %>
  <% end %>
</h5>

  <% if current_user %>
    <h3><%= link_to 'Signout', destroy_user_session_path, :method => :delete %></h3>
  <% else %>
    <h3><%= link_to 'Signup', new_user_registration_path %></h3>
    <h3><%= link_to 'Login', new_user_session_path %></h3>
  <% end %>

  <a class = "nav" href = "/posts">All Posts</a>
  <a class = "nav" href = "/posts/new">New Post</a>
</header>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/posts/edit.html.erb
<h2>Edit Post</h2>

<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :content%>
  <%= f.text_area :content, size: "90x12" %>

  <%= f.submit %>
<% end %>

<%= form_for @post, method: :delete do |f| %>
  <%= f.submit "Delete!", class: "delete" %>
<% end %>

app/views/posts/index.html.erb
<h2>Posts</h2>
<% @posts.each do |post| %>
  <li> <%= link_to post.title, post %>
      <p><%= post.content %></p>
      <p>Author: <%= post.author %></p>
      <hr>

  </li>
<% end %>

app/views/posts/new.html.erb
<h2>New Post</h2>
<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :content%>
  <%= f.text_area :content, size: "90x12" %>

  <%= f.label :author %>
  <%= f.text_field :author %>

  <%= f.submit "Submit Post" %>
<% end %>

app/views/posts/show.html.erb
<h2><%=@post.title%>
  <%if (@post.user == current_user) %>
  <%=link_to "(edit)", edit_post_path(@post)%>
  <% end %>
</h2>

<li>
<p><%=@post.content%></p>
<p><%=@post.author%></p>
<p>Created: <%= @post.created_at %>,  Last updated: <%= @post.updated_at %></p>
</li>

<h4>Comments <%=link_to "(add)", new_post_comment_path(@post)%></h4>


<% @post.comments.each do |comment| %>
  <li><p> <%= link_to comment.subject, post_comment_path(@post, comment) %></p>
      <p><%= comment.content %></p>
      <p>Author: <%= comment.author %></p>
      <p>Created: <%= comment.created_at %>,  Last updated: <%= comment.updated_at %></p>
  </li>
  <% end %>